### ISSUE TITLE
error on bestiapop.py, silo_connector.py and generic.py

### ISSUE THREAD

**Issue by daSilva5** [JJguri/bestiapop#45]
Hi,
Thank you for your package.  I am running your example from https://github.com/JJguri/bestiapop/blob/master/sample-data/example-local.ipynb.
The installed version using pip is bestiapop          3.0.10, I am running it in an environment I created only for this package. And I do not know if it is relevant, but I am using R markdown with a {python} chunk.
I get the following errors:

```
2024-11-06 11:53:43 - POPBEAST - Extracting data and converting to met format
Fetching data for -27.49521/152.806398
Fetching and Parsing Data:   0%|          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "C:\Users\...~1\AppData\Local\ANACON~1\envs\CONDA_~1\Lib\site-packages\bestiapop\bestiapop.py", line 579, in process_records
    final_df_latlon_tuple_list = silo.generate_climate_dataframe_from_silo_cloud_api(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...~1\AppData\Local\ANACON~1\envs\CONDA_~1\Lib\site-packages\bestiapop\connectors\silo_connector.py", line 317, in generate_climate_dataframe_from_silo_cloud_api
    total_climate_df = total_climate_df.append(var_year_lat_lon_df)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\....~1\AppData\Local\ANACON~1\envs\CONDA_~1\Lib\site-packages\pandas\core\generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?

```
 

Thanks

**Comment by Joaquin-Urruti** [comment]
Hi Jony!

I've got the same error:

Traceback (most recent call last):
  File "/Users/ju/bestiapop/bestiapop/bestiapop.py", line 677, in main
    if coordinates_range:
       ^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'coordinates_range' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ju/bestiapop/bestiapop/bestiapop.py", line 731, in <module>
    main()
  File "/Users/ju/bestiapop/bestiapop/bestiapop.py", line 717, in main
    myclimatebeast.process_records(pargs.action)
  File "/Users/ju/bestiapop/bestiapop/bestiapop.py", line 596, in process_records
    final_df_latlon_tuple_list = nasapower.generate_climate_dataframe_from_nasapower_cloud_api(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ju/bestiapop/bestiapop/connectors/nasapower_connector.py", line 350, in generate_climate_dataframe_from_nasapower_cloud_api
    total_climate_df = total_climate_df.append(var_year_lat_lon_df)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ju/bestiapop/.venv/lib/python3.12/site-packages/pandas/core/generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?
